druid.service=druid/middleManager
druid.plaintextPort=8091

druid.worker.capacity=7
druid.worker.baseTaskDirs=[\"var/druid/task\"]

druid.indexer.runner.javaOptsArray=["-server","-Xms1g","-Xmx1g","-XX:MaxDirectMemorySize=1g","-Duser.timezone=UTC","-Dfile.encoding=UTF-8","-XX:+ExitOnOutOfMemoryError","-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager", "-Daws.region=${region}"]

druid.indexer.runner.maxZnodeBytes=15728640

druid.server.http.numThreads=100

druid.indexer.fork.property.druid.processing.numMergeBuffers=2
druid.indexer.fork.property.druid.processing.buffer.sizeBytes=100MiB
druid.indexer.fork.property.druid.processing.numThreads=1

druid.indexer.task.hadoopWorkingPath=var/druid/hadoop-tmp