druid.service=druid/coordinator
druid.plaintextPort=8081

druid.server.http.numThreads=100
druid.indexer.runner.workerSyncNumThreads=6

druid.coordinator.startDelay=PT10S
druid.coordinator.period=PT5S
druid.manager.segments.pollDuration=PT5S

druid.indexer.logs.kill.enabled=true
druid.indexer.logs.kill.delay=14400000
druid.indexer.logs.kill.durationToRetain=86400000

druid.coordinator.kill.on=true
druid.coordinator.kill.period=P1D
druid.coordinator.kill.durationToRetain=P4D
druid.coordinator.kill.bufferPeriod=P7D

druid.coordinator.kill.audit.on=true
druid.coordinator.kill.audit.period=P1D
druid.coordinator.kill.audit.durationToRetain=P7D

druid.manager.config.pollDuration=PT10M
druid.indexer.runner.maxZnodeBytes=15728640

druid.coordinator.asOverlord.enabled=true
druid.coordinator.asOverlord.overlordService=druid/overlord

druid.indexer.queue.startDelay=PT5S

druid.indexer.storage.type=metadata

druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.OshiSysMonitor", "org.apache.druid.server.metrics.TaskCountStatsMonitor"]