druid.service=druid/router
druid.plaintextPort=8888

druid.router.http.numConnections=80
druid.router.http.readTimeout=PT5M
druid.router.http.numMaxThreads=80

druid.router.defaultBrokerServiceName=druid/broker
druid.router.coordinatorServiceName=druid/coordinator

druid.router.managementProxy.enabled=true