druid.service=druid/historical
druid.plaintextPort=8083

druid.server.http.numThreads=100

druid.processing.buffer.sizeBytes=900MiB
druid.processing.numMergeBuffers=5
druid.processing.numThreads=5
druid.processing.tmpDir=var/druid/processing

druid.query.groupBy.maxOnDiskStorage=10000000000
druid.query.groupBy.maxMergingDictionarySize=10000000000

druid.segmentCache.locationSelector.strategy=mostAvailableSize
druid.segmentCache.numLoadingThreads=2

druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize":"500g"}]

druid.historical.cache.useCache=true
druid.historical.cache.populateCache=true
druid.cache.type=caffeine
druid.cache.sizeInBytes=1GiB
druid.processing.fifo=false

druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.OshiSysMonitor", "org.apache.druid.server.metrics.HistoricalMetricsMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]