druid.service=druid/broker
druid.plaintextPort=8082

druid.server.http.numThreads=80

druid.broker.http.numConnections=70
druid.broker.http.maxQueuedBytes=12MiB

druid.processing.buffer.sizeBytes=900MiB
druid.processing.numMergeBuffers=6
druid.processing.tmpDir=var/druid/processing

druid.processing.fifo=false

druid.server.http.defaultQueryTimeout=600000

druid.server.http.maxSubqueryRows=4000000
druid.sql.planner.useApproximateTopN=false
druid.sql.planner.useApproximateCountDistinct=false
druid.sql.planner.useGroupingSetForExactDistinct=true

druid.broker.cache.useResultLevelCache=false
druid.broker.cache.populateResultLevelCache=false
druid.sql.planner.metadataSegmentCacheEnable=false

druid.monitoring.monitors=["org.apache.druid.java.util.metrics.JvmMonitor", "org.apache.druid.java.util.metrics.OshiSysMonitor", "org.apache.druid.server.metrics.QueryCountStatsMonitor"]